definitions:
  model.User:
    properties:
      create_at:
        description: 创建时间
        type: integer
      id:
        description: ID
        type: integer
      nickname:
        description: 用户呢称
        type: string
      password:
        description: 密码
        type: string
      phone:
        description: 手机号
        type: string
      updated_at:
        description: 更新时间
        type: integer
      username:
        description: 用户名称
        type: string
    type: object
  response.Result:
    properties:
      code:
        description: 业务码
        type: integer
      data:
        description: 业务消息体
      msg:
        description: 业务消息
        type: string
    type: object
info:
  contact: {}
paths:
  /api/user/create:
    post:
      consumes:
      - application/json
      description: 用户创建
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
      summary: 用户创建
      tags:
      - 用户管理
  /api/user/details:
    get:
      consumes:
      - application/json
      description: 用户详情
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: 用户详情
      tags:
      - 用户管理
swagger: "2.0"
