definitions:
  response.Result:
    properties:
      code:
        description: 业务码
        type: integer
      data:
        description: 业务消息体
      msg:
        description: 业务消息
        type: string
    type: object
info:
  contact: {}
paths:
  /user/create:
    post:
      consumes:
      - application/json
      description: hello echo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
      summary: 用户创建
      tags:
      - 用户管理
  /user/details:
    get:
      consumes:
      - application/json
      description: hello echo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
      summary: 用户详情
      tags:
      - 用户管理
swagger: "2.0"
