definitions:
  api.R:
    properties:
      code:
        example: "0"
        type: string
      data: {}
      msg:
        example: 信息
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: gin-skeleton 示例项目
  title: gin-skeleton
  version: "1.0"
paths:
  /user/create:
    post:
      consumes:
      - application/json
      description: hello echo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.R'
      summary: 用户创建
      tags:
      - 文章管理
  /user/details:
    get:
      consumes:
      - application/json
      description: hello echo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.R'
      summary: 用户详情
      tags:
      - 文章管理
swagger: "2.0"
